<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link href="Css/styles.css" rel="stylesheet" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
   
   <title>Contacts Home</title>
   
<script>
    var showWidth = 1;
    if (showWidth == 1) {

        $(document).ready(function () {
            $(window).resize(function () {
                var width = $(window).width();
                document.getElementById('lblwidth').innerHTML = "Browser-Width:" + width.toString();
            });
        });
    }

    </script>
</head>
<body>
    <div id="lblwidth"></div>
    
        <header class="mainheader">
            <div class="container-fluid text-center">
                <a ID="signout"  href="signout.aspx" >SignOut</a>
                    <h1 >LoL Contact Manager</h1>  
                <p>A Place to keep your Contacts safe and secure</p>
               
            </div>   
       </header>
       <div class="container-fluid">
           <div class="row">
               <div class="col-xs-12">
    <nav id="main-nav">
        <ul >
            <li id="home"><a href="Default.aspx">Home</a></li>
            <li><a href="Addcontact.aspx">Add Contacts</a></li>
            <li><a href="Contacts.aspx">Search</a></li>
            <li><a href="About.html">About Us</a></li>
            <li><a href="Contactus.html">Contact Us</a></li>
       </ul>      
    </nav>
    </div>
    </div>
    <div class="row">
     <div id="main" class="col-sm-12">
        
             <header><h2>Contacts</h2></header>
             <p>In this tutorial we will discuss how to stat development for android wear/watch.
Things you need to know:
Wear App Components
Wear apps can be composed of several components, these components can be used as per requirement. 
1.	Notifications:
Bridge Notifications: These notifications are provided by the handheld to the wearable utilizing the standard Android notifications.
Contextual Notifications: These notifications are generated by the wearable and can appear at an appropriate contextual point.

2.	Full screen UI app:
2D Picker: This is a design pattern that is being recommended by the android developer community when applicable. It permits the user to choose from a set of items.
Custom Layout: Custom layouts can also be used when demanded by the app.

Let's get started now….
(Note: We will be using Android Studio for this tutorial)
Open Android studio, you will get the welcome screen.
After Android studio is opened, start with adding a virtual device.
Adding an Android Wear Emulator
1.	Go to AVD Manager by clicking on Tools Android AVD Manager.
</p>
       
     </div>
     </div>
     </div>
     <aside id="sidebar" class="container footer navbar-default navbar-bottom">
        <div class="row">
        <div class="col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-12 col-xs-offset-0">
             <h4 class="text-center">Social Links</h4>
                    <div class="col-sm-2 col-xs-2"> <a href="https://www.facebook.com"> <img src="Images/fbook.png" alt="facebook"></a> </div>
                    <div class="col-sm-2 col-xs-2""> <a href="https://www.twitter.com"> <img src="Images/twiter.png" alt="twitter"></a> </div>
               
                
                    <div class="col-sm-2 col-xs-2""> <a href="https://www.youtube.com"> <img src="Images/youtube.png" alt="youtube"></a> </div>
                    <div class="col-sm-2 col-xs-2""> <a href="https://www.linkedin.com"> <img src="Images/linkedin.jpg" alt="linkedin"></a> </div>
             
                    <div class="col-sm-2 col-xs-2""> <a href="https://www.yahoo.com"> <img src="Images/yahoo.jpg" alt="yahoo"></a> </div>
                    <div class="col-sm-2 col-xs-2""> <a href="https://www.gmail.com"> <img src="Images/google.png" alt="gplus"></a> </div>
        </div>
        </div>
     </aside>
   
</body>
</html>